version: "3.7"

services:
  web1:
    build: ./NodeGoat
    hostname: web1
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    expose: 
        - 4000
  web2:
    build: ./NodeGoat
    hostname: web2
    environment:
      NODE_ENV:
      MONGODB_URI: mongodb://mongo:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo 27017 && echo 'mongo is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    expose: 
        - 4000

  mongo:
    image: mongo:latest
    user: mongodb
    expose:
      - 27017

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1
    - web2
