name: Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: docker-compose build
    - name: Start Docker-Compose
      run: docker-compose up -d
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    - name: Smoke test 1
      run: curl localhost:80 
    - name: Smoke test 2
      run: curl localhost:4000
    - name: Smoke test 3
      run: curl web1:80 
      
