name: Docker Images
# Access Key = AKIAICTMZ   TTXEHB   TKABC
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: docker-compose build
    